#!/usr/bin/env bash
# =====================================================================
# CALM-Row end-to-end runner (Linux).
#   prepare CRDLD/CRBD -> train base+calm (xN seeds) -> A/B eval -> stats -> assets
# Run from the repo root:  bash run_all.sh
# Override via env, e.g.:  EPOCHS=2 SEEDS=0 DEVICE=0 bash run_all.sh   # quick smoke
# Needs the torch env active (pip install -r requirements.txt). Do NOT pip-install
# ultralytics — this uses the local fork; always run from the repo root.
#
# LaTeX is NOT required here: on a Linux box without latexmk the script generates
# paper/tables + paper/figures (tracked by git) and stops short of compiling.
# Compile the PDF on Windows:  PUSH_ASSETS=1 bash run_all.sh  (auto commit+push),
# then on Windows  git pull  and  cd paper && latexmk -pdf main.tex.
# =====================================================================
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(pwd)"

# ---- config (env-overridable) ----
MODEL="${MODEL:-yolov8n.pt}"      # .pt = COCO-pretrained init (auto-downloads); .yaml = from scratch
EPOCHS="${EPOCHS:-200}"
IMGSZ="${IMGSZ:-640}"
DEVICE="${DEVICE:-0}"             # "0" GPU, or "cpu"
SEEDS="${SEEDS:-0 1 2 3 4}"
NBOXES="${NBOXES:-8}"   # y-bands (boxes per row); fewer+larger boxes train more stably
CONF="${CONF:-0.25}"    # eval-time conf for the guidance harness. NOTE (verified): select_central
                        # gates boxes by x-CORRIDOR, not by score, so a very LOW conf injects false
                        # centroids into the central corridor and worsens heading. Keep moderate.
                        # After the full retrain, sweep CONF in {0.15 0.25 0.35} and keep the value
                        # with the lowest median heading-error (not just the highest frames-with-line).
RUNDIR="${RUNDIR:-runs/detect}"
OUT="${OUT:-results}"
mkdir -p "$OUT"
echo "[cfg] MODEL=$MODEL EPOCHS=$EPOCHS IMGSZ=$IMGSZ DEVICE=$DEVICE SEEDS='$SEEDS' OUT=$OUT"

# ---- 0. dataset config with ABSOLUTE path (avoids Ultralytics datasets_dir lookup) ----
DATA="$ROOT/datasets/CRDLD_yolo.local.yaml"
cat > "$DATA" <<EOF
# auto-generated by run_all.sh (machine-local; gitignored)
path: $ROOT/datasets/CRDLD_yolo
train: images/train
val: images/val
test: images/test
nc: 1
names:
  0: crop_row
EOF
echo "[data] $DATA -> path: $ROOT/datasets/CRDLD_yolo"

# ---- 1. preprocess (idempotent; FORCE_PREP=1 to redo) ----
VAL_DIR="$ROOT/datasets/CRDLD_yolo/images/val"
if [ "${FORCE_PREP:-0}" = "1" ] || [ ! -d "$VAL_DIR" ] || [ -z "$(ls -A "$VAL_DIR" 2>/dev/null || true)" ]; then
  echo "[prep] building CRDLD_yolo detection set from line-masks..."
  python prepare_crdld.py --root datasets/CRDLD --splits train validation test \
    --out-images datasets/CRDLD_yolo/images --out-labels datasets/CRDLD_yolo/labels --n-boxes "$NBOXES"
else
  echo "[prep] CRDLD_yolo present -> skip (FORCE_PREP=1 to rebuild)"
fi
echo "[prep] CRBD GT lines from .tmg..."
python crbd_gt.py --root datasets/CRBD --out datasets/CRDLD_yolo/labels/gtlines_crbd.json || echo "[warn] CRBD GT step failed (cross-dataset eval will be skipped)"

GTTEST="$ROOT/datasets/CRDLD_yolo/labels/gtlines_test.json"
GTCRBD="$ROOT/datasets/CRDLD_yolo/labels/gtlines_crbd.json"

# ---- 2. train + A/B eval per seed ----
for S in $SEEDS; do
  echo "================= SEED $S ================="
  python train.py --model "$MODEL" --data "$DATA" --epochs "$EPOCHS" --imgsz "$IMGSZ" \
    --device "$DEVICE" --name "base_v8n_s$S" --seed "$S"
  python train.py --model "$MODEL" --data "$DATA" --epochs "$EPOCHS" --imgsz "$IMGSZ" \
    --device "$DEVICE" --calm_row --calm_calib_gain 0.5 --calm_line_gain 1.0 --name "calm_v8n_s$S" --seed "$S"

  BASE="$RUNDIR/base_v8n_s$S/weights/best.pt"
  CALM="$RUNDIR/calm_v8n_s$S/weights/best.pt"

  # arms share the BASE checkpoint; B uses the CALM checkpoint.
  #   equalLS = non-robust equal (weak baseline A) | ransac = robust equal (STRONG baseline)
  #   irls    = robust equal IRLS (ablation: isolates robustness from weighting)
  #   calm    = precision + Huber-IRLS (the proposal, B0) | qual = conf-weighted | oracle = upper bound
  for R in equalLS ransac irls calm qual oracle; do
    python eval_guidance.py --weights "$BASE" --device "$DEVICE" --conf "$CONF" \
      --images datasets/CRDLD_yolo/images/test --gt-json "$GTTEST" \
      --readout "$R" --out "$OUT/${R}_s$S.csv" --calib-out "$OUT/calib_${R}_s$S.csv"
  done
  python eval_guidance.py --weights "$CALM" --device "$DEVICE" --conf "$CONF" \
    --images datasets/CRDLD_yolo/images/test --gt-json "$GTTEST" \
    --readout calm --out "$OUT/B_s$S.csv" --calib-out "$OUT/calib_B_s$S.csv"

  # cross-dataset transfer (CRDLD-trained CALM -> CRBD, no retrain)
  if [ -f "$GTCRBD" ]; then
    python eval_guidance.py --weights "$CALM" --device "$DEVICE" --conf "$CONF" \
      --images datasets/CRBD/Images --gt-json "$GTCRBD" \
      --readout calm --out "$OUT/B_crbd_s$S.csv" || echo "[warn] CRBD eval failed (seed $S)"
  fi

  echo "----- stats seed $S (confirmatory family m=4) -----"
  echo "[H1] calm vs equalLS (proposal vs weak baseline):"
  python stats_ab.py "$OUT/equalLS_s$S.csv" "$OUT/calm_s$S.csv" --metric heading_err_deg --family-size 4 || true
  echo "[H2] calm vs RANSAC (proposal vs STRONG baseline -- the decisive test):"
  python stats_ab.py "$OUT/ransac_s$S.csv"  "$OUT/calm_s$S.csv" --metric heading_err_deg --family-size 4 || true
  echo "[Ablation] calm vs irls (does PRECISION add beyond robustness?):"
  python stats_ab.py "$OUT/irls_s$S.csv"    "$OUT/calm_s$S.csv" --metric heading_err_deg --family-size 4 || true
  echo "[Training] B vs B0 (does calm-training help? must be != 0 now that the no-op is fixed):"
  python stats_ab.py "$OUT/calm_s$S.csv"    "$OUT/B_s$S.csv"    --metric heading_err_deg --family-size 4 || true
done

# ---- 2b. calibration gate: is the DFL variance even informative? (decides fix vs pivot) ----
echo "===== calibration gate (Spearman rho of predicted sigma vs realised error) ====="
python calib_gate.py "$OUT"/calib_calm_s*.csv || echo "[warn] calib gate failed"

# ---- 3. paper assets: qualitative overlays + tables + figures + compile ----
FS=$(set -- $SEEDS; echo "$1")
CALM0="$RUNDIR/calm_v8n_s$FS/weights/best.pt"
if [ -f "$CALM0" ]; then
  echo "[assets] qualitative overlays (first seed)..."
  python eval_guidance.py --weights "$CALM0" --device "$DEVICE" --conf "$CONF" \
    --images datasets/CRDLD_yolo/images/test --gt-json "$GTTEST" \
    --readout calm --out "$OUT/_overlay_tmp.csv" \
    --overlay-dir paper/figures/qualitative --overlay-n 6 --limit 60 || echo "[warn] overlay step failed"
fi
echo "[assets] aggregating -> paper/tables + paper/figures ..."
python make_paper_assets.py --results "$OUT" --paper paper || echo "[warn] asset generation failed"
if command -v latexmk >/dev/null 2>&1; then
  echo "[assets] compiling paper/main.pdf ..."
  ( cd paper && latexmk -pdf -interaction=nonstopmode -f main.tex >/tmp/calmrow_latex.log 2>&1 ) \
    && echo "[assets] -> paper/main.pdf" || echo "[warn] LaTeX issues — see /tmp/calmrow_latex.log"
else
  # No LaTeX here (Linux training box). Tables + figures are tracked by git, so the
  # handoff to the Windows compile machine is just a commit+push -> pull.
  echo "[assets] no latexmk here (Linux) — paper/tables + paper/figures are ready to compile on Windows."
  if [ "${PUSH_ASSETS:-0}" = "1" ]; then
    echo "[assets] PUSH_ASSETS=1 -> committing + pushing paper assets..."
    git add -f paper/tables paper/figures/fig_*.pdf 2>/dev/null || true
    if git diff --cached --quiet; then
      echo "[assets] nothing changed — skip commit."
    else
      git commit -q -m "results: paper tables + figures (auto from run_all.sh on Linux)" \
        && git push && echo "[assets] pushed -> on Windows: git pull, then compile paper/main.tex" \
        || echo "[warn] commit/push failed — push the assets manually."
    fi
  else
    echo "  Next, to compile on Windows:"
    echo "    (Linux)   git add -f paper/tables paper/figures/fig_*.pdf && git commit -m results && git push"
    echo "    (Windows) git pull   then   cd paper && latexmk -pdf main.tex   (or your LaTeX editor)"
    echo "  Tip: run with  PUSH_ASSETS=1 bash run_all.sh  to auto commit+push the assets."
  fi
fi

echo "[done] checkpoints in $RUNDIR/ ; CSVs+stats in $OUT/ ; tables in paper/tables/ ; figures in paper/figures/"
