#!/usr/bin/env bash
# =====================================================================
# CALM-Row end-to-end runner (Linux).
#   prepare CRDLD/CRBD -> train base+calm (xN seeds) -> A/B eval -> stats
# Run from the repo root:  bash run_all.sh
# Override via env, e.g.:  EPOCHS=2 SEEDS=0 DEVICE=0 bash run_all.sh   # quick smoke
# Needs the torch env active (pip install -r requirements.txt). Do NOT pip-install
# ultralytics — this uses the local fork; always run from the repo root.
# =====================================================================
set -euo pipefail
cd "$(dirname "$0")"
ROOT="$(pwd)"

# ---- config (env-overridable) ----
MODEL="${MODEL:-yolov8n.pt}"      # .pt = COCO-pretrained init (auto-downloads); .yaml = from scratch
EPOCHS="${EPOCHS:-200}"
IMGSZ="${IMGSZ:-640}"
DEVICE="${DEVICE:-0}"             # "0" GPU, or "cpu"
SEEDS="${SEEDS:-0 1 2 3 4}"
NBOXES="${NBOXES:-6}"
RUNDIR="${RUNDIR:-runs/detect}"
OUT="${OUT:-results}"
mkdir -p "$OUT"
echo "[cfg] MODEL=$MODEL EPOCHS=$EPOCHS IMGSZ=$IMGSZ DEVICE=$DEVICE SEEDS='$SEEDS' OUT=$OUT"

# ---- 0. dataset config with ABSOLUTE path (avoids Ultralytics datasets_dir lookup) ----
DATA="$ROOT/datasets/CRDLD_yolo.local.yaml"
cat > "$DATA" <<EOF
# auto-generated by run_all.sh (machine-local; gitignored)
path: $ROOT/datasets/CRDLD_yolo
train: images/train
val: images/val
test: images/test
nc: 4
names:
  0: near
  1: mid_near
  2: mid_far
  3: far
EOF
echo "[data] $DATA -> path: $ROOT/datasets/CRDLD_yolo"

# ---- 1. preprocess (idempotent; FORCE_PREP=1 to redo) ----
VAL_DIR="$ROOT/datasets/CRDLD_yolo/images/val"
if [ "${FORCE_PREP:-0}" = "1" ] || [ ! -d "$VAL_DIR" ] || [ -z "$(ls -A "$VAL_DIR" 2>/dev/null || true)" ]; then
  echo "[prep] building CRDLD_yolo detection set from line-masks..."
  python prepare_crdld.py --root datasets/CRDLD --splits train validation test \
    --out-images datasets/CRDLD_yolo/images --out-labels datasets/CRDLD_yolo/labels --n-boxes "$NBOXES"
else
  echo "[prep] CRDLD_yolo present -> skip (FORCE_PREP=1 to rebuild)"
fi
echo "[prep] CRBD GT lines from .tmg..."
python crbd_gt.py --root datasets/CRBD --out datasets/CRDLD_yolo/labels/gtlines_crbd.json || echo "[warn] CRBD GT step failed (cross-dataset eval will be skipped)"

GTTEST="$ROOT/datasets/CRDLD_yolo/labels/gtlines_test.json"
GTCRBD="$ROOT/datasets/CRDLD_yolo/labels/gtlines_crbd.json"

# ---- 2. train + A/B eval per seed ----
for S in $SEEDS; do
  echo "================= SEED $S ================="
  python train.py --model "$MODEL" --data "$DATA" --epochs "$EPOCHS" --imgsz "$IMGSZ" \
    --device "$DEVICE" --name "base_v8n_s$S" --seed "$S"
  python train.py --model "$MODEL" --data "$DATA" --epochs "$EPOCHS" --imgsz "$IMGSZ" \
    --device "$DEVICE" --calm_row --calm_calib_gain 0.5 --calm_line_gain 1.0 --name "calm_v8n_s$S" --seed "$S"

  BASE="$RUNDIR/base_v8n_s$S/weights/best.pt"
  CALM="$RUNDIR/calm_v8n_s$S/weights/best.pt"

  # arms A/A'/B0/qual/oracle share the BASE checkpoint; B uses the CALM checkpoint
  for R in equalLS ransac calm qual oracle; do
    python eval_guidance.py --weights "$BASE" --device "$DEVICE" \
      --images datasets/CRDLD_yolo/images/test --gt-json "$GTTEST" \
      --readout "$R" --out "$OUT/${R}_s$S.csv" --calib-out "$OUT/calib_${R}_s$S.csv"
  done
  python eval_guidance.py --weights "$CALM" --device "$DEVICE" \
    --images datasets/CRDLD_yolo/images/test --gt-json "$GTTEST" \
    --readout calm --out "$OUT/B_s$S.csv" --calib-out "$OUT/calib_B_s$S.csv"

  # cross-dataset transfer (CRDLD-trained CALM -> CRBD, no retrain)
  if [ -f "$GTCRBD" ]; then
    python eval_guidance.py --weights "$CALM" --device "$DEVICE" \
      --images datasets/CRBD/Images --gt-json "$GTCRBD" \
      --readout calm --out "$OUT/B_crbd_s$S.csv" || echo "[warn] CRBD eval failed (seed $S)"
  fi

  echo "----- stats seed $S -----"
  echo "[H1] B (CALM) vs A (equal-weight LS), heading error:"
  python stats_ab.py "$OUT/equalLS_s$S.csv" "$OUT/B_s$S.csv"   --metric heading_err_deg --family-size 3 || true
  echo "[B0 vs A] weighting-only gain:"
  python stats_ab.py "$OUT/equalLS_s$S.csv" "$OUT/calm_s$S.csv" --metric heading_err_deg --family-size 3 || true
  echo "[B vs B0] training-adds gain:"
  python stats_ab.py "$OUT/calm_s$S.csv" "$OUT/B_s$S.csv"       --metric heading_err_deg --family-size 3 || true
done

echo "[done] checkpoints in $RUNDIR/ ; per-frame CSVs + stats in $OUT/"
echo "Aggregate across seeds (mean+/-std + paired tests) per EXPERIMENT_PLAN Sec 6 to fill the result tables."
